// Generated by scripts/generate.py. Do not edit.

package io.github.tepmex.cjklists.kt.zh.subtlexch

val top1000: List<String> = Words.top1000
val second1000: List<String> = Words.second1000
val third1000: List<String> = Words.third1000
val top10000: List<String> = Words.top10000
